language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: master
